# configuration_file.yml

# Definition of the categories to be included in the changelog
categories:
    - title: "ğŸš€ Features"
      labels:
          - "feature"
          - "enhancement"

    - title: "ğŸ› Bug Fixes"
      labels:
          - "bug"
          - "bugfix"
          - "fix"

    - title: "ğŸ§° Maintenance"
      labels:
          - "maintenance"
          - "refactor"
          - "chore"

    - title: "ğŸ“– Documentation"
      labels:
          - "documentation"

    - title: "ğŸ§ª Tests"
      labels:
          - "test"
          - "tests"

excluded_labels:
    - "skip-changelog"

sort: DESC
include_author: true
include_labels: true
include_hash: false

# The template to be used for the changelog
template: |
    ## [{{ version }} - {{ date }}]
    {{#each categories}}
    ### {{ title }}
    {{#each commits}}
     - {{message}} ([@{{author}}]{{author_url}})
    {{/each}}
    {{/each}}

# Version Strategy
version_resolver:
    major:
        labels:
            - "breaking"
            - "major"

    minor:
        labels:
            - "feature"
            - "enhancement"
            - "minor"

    patch:
        labels:
            - "bug"
            - "bugfix"
            - "fix"
            - "maintenance"
            - "refactor"
            - "chore"
            - "documentation"
            - "test"
            - "tests"
